# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d86db29ed89eea5ef53b8829a674ce8dcede0d72d936a1148c414a205ac3e3f8e50ba0729148a88c3f30e52d593276ad2e028b4012f7f5fcb44011ddb9eff56

test:
  secret_key_base: 54b06ea1b81556aa2ec576929a407848ed75d8494b0085063831a55bed3ba9a4c6a20ba52c4576faa99ceec1807ff47e4b5ba6c847fcef2c2c2311ca0e42ae73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
